### ISSUE TITLE
Issue tracker?

### ISSUE THREAD

**Issue by inktomi** [kiibohd/kiibohd-core#6]
Hi - 

I'm sort of interested in learning Rust, and it seems like it might make sense to refactor some C code to Rust. I think there's still some of that going on? If so, where are the open issues stored for this project? Or feature requests? What is the process for contributing?

**Comment by haata** [comment]
@inktomi reach out to me (HaaTa) on our discord channel, I'll give you a run down: https://discord.com/invite/WS65mtc

Over the next few days, I'm also going to start filling out the issue trackers now that the design has mostly settled.
